### ISSUE TITLE
Too many occurrence of the `IllegalStateException` on a part of devices.

### ISSUE THREAD

**Issue by KazumiHARADA** [googlesamples/androidtv-Leanback#124]
Hello leanback development team,

I've found the issue of the `IllegalStateException ` occurred on only the LifeStick.
According logcats, it seems to be occurred in the leanback library.
Is it possibility that our implementation is mistaken? If so, could you how to fix it.
(Currently, our app has committed the `BrowseFragment` in the layout resource file)

Error details :
``` 
android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
       at android.app.BackStackRecord.commit(BackStackRecord.java:671)
       at android.support.v17.leanback.app.BrowseFragment.swapToMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment.replaceMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment.createMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment$SetSelectionRunnable.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
#0. Crashed: main
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
       at android.app.BackStackRecord.commit(BackStackRecord.java:671)
       at android.support.v17.leanback.app.BrowseFragment.swapToMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment.replaceMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment.createMainFragment(Unknown Source)
       at android.support.v17.leanback.app.BrowseFragment$SetSelectionRunnable.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at 
```

**Comment by jurajTomko** [comment]
Same issue here. Please respond.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
