### ISSUE TITLE
android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v17.leanback.widget.VerticalGridView

### ISSUE THREAD

**Issue by ChandrakantOmn** [googlesamples/androidtv-Leanback#135]
Whenever I am trying to implement   " PrefFragment extends LeanbackPreferenceFragment "  I am getting 
this error and app crashing

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.omniwyse.user.tvluncherrd/com.omniwyse.user.tvluncherrd.SettingsActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v17.leanback.widget.VerticalGridView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v17.leanback.widget.VerticalGridView
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.support.v17.leanback.widget.VerticalGridView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.support.v17.preference.BaseLeanbackPreferenceFragment.onCreateRecyclerView(BaseLeanbackPreferenceFragment.java:42)
        at android.support.v14.preference.PreferenceFragment.onCreateView(PreferenceFragment.java:270)
        at android.support.v17.preference.LeanbackPreferenceFragment.onCreateView(LeanbackPreferenceFragment.java:54)
        at android.app.Fragment.performCreateView(Fragment.java:2522)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
        at android.app.Fragment.performActivityCreated(Fragment.java:2537)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
        at android.app.Activity.performCreate(Activity.java:7143)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
2018-10-25 23:16:18.659 4590-4590/com.omniwyse.user.tvluncherrd E/AndroidRuntime:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v17.leanback.widget.GridLayoutManager.onRtlPropertiesChanged(int)' on a null object reference
        at android.support.v17.leanback.widget.BaseGridView.onRtlPropertiesChanged(BaseGridView.java:1089)
        at android.view.View.resolvePadding(View.java:18146)
        at android.view.ViewGroup.resolvePadding(ViewGroup.java:7305)
        at android.view.View.initializeScrollbarsInternal(View.java:6067)
        at android.view.View.<init>(View.java:5569)
        at android.view.ViewGroup.<init>(ViewGroup.java:659)
        at android.view.ViewGroup.<init>(ViewGroup.java:655)
        at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:651)
        at android.support.v17.leanback.widget.BaseGridView.<init>(BaseGridView.java:217)
        at android.support.v17.leanback.widget.VerticalGridView.<init>(VerticalGridView.java:52)
        at android.support.v17.leanback.widget.VerticalGridView.<init>(VerticalGridView.java:48)
        	... 40 more

**Comment by niunno** [comment]
Same problem with Androidx

**Comment by vitaliyFora** [comment]
Have the same problem.
I solved it by adding a [theme from sample](https://github.com/googlesamples/leanback-showcase/blob/6a643637f66ea00ffdce9f4d1a360ca20301c75d/app/src/main/AndroidManifest.xml#L55)  to SettingActivity in which I start LeanbackSettingsFragment.

**Comment by stari4ek** [comment]
```
2019-08-06 09:04:18.594 18233-18233/by.stari4ek.tvirl.debug E/UncaughtExceptionHandler: Uncaught exception
    android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class androidx.leanback.widget.VerticalGridView
    Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class androidx.leanback.widget.VerticalGridView
    Caused by: java.lang.reflect.InvocationTargetException: null
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidx.leanback.preference.BaseLeanbackPreferenceFragmentCompat.onCreateRecyclerView(BaseLeanbackPreferenceFragmentCompat.java:73)
        at androidx.preference.PreferenceFragmentCompat.onCreateView(PreferenceFragmentCompat.java:208)
        at androidx.leanback.preference.LeanbackPreferenceFragmentCompat.onCreateView(LeanbackPreferenceFragmentCompat.java:54)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.leanback.widget.GridLayoutManager.onRtlPropertiesChanged(int)' on a null object reference
        at androidx.leanback.widget.BaseGridView.onRtlPropertiesChanged(BaseGridView.java:1097)
        at android.view.View.resolvePadding(View.java:18146)
        at android.view.ViewGroup.resolvePadding(ViewGroup.java:7305)
        at android.view.View.initializeScrollbarsInternal(View.java:6067)
        at android.view.View.<init>(View.java:5569)
        at android.view.ViewGroup.<init>(ViewGroup.java:659)
        at android.view.ViewGroup.<init>(ViewGroup.java:655)
        at androidx.recyclerview.widget.RecyclerView.<init>(RecyclerView.java:651)
        at androidx.leanback.widget.BaseGridView.<init>(BaseGridView.java:221)
        at androidx.leanback.widget.VerticalGridView.<init>(VerticalGridView.java:52)
        at androidx.leanback.widget.VerticalGridView.<init>(VerticalGridView.java:48)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
```
same stuff with `alpha02`
```
implementation 'androidx.leanback:leanback:1.1.0-alpha02'
implementation 'androidx.leanback:leanback-preference:1.1.0-alpha02'

**Comment by cosart** [comment]
Had the same issue, turns out you cannot have scrollbars with VerticalGridView...

**Comment by aeoloslee** [comment]
Hi,there! Have you solved this problem?

**Comment by ChandrakantOmn** [comment]
yeah

**Comment by ChandrakantOmn** [comment]
Try to change the theme for SettingActivity in manifist
follw this link
https://github.com/googlesamples/leanback-showcase/tree/6a643637f66ea00ffdce9f4d1a360ca20301c75d

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there. In addition, the new location can accept Pull Requests (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
