### ISSUE TITLE
Content search seems to be broken

### ISSUE THREAD

**Issue by JamieAndresakis** [googlesamples/androidtv-Leanback#25]
When running the sample app on a nexus player no content can be brought up using the google search. I can see in the logcat the following error. 

1822-1838/com.example.android.leanback E/JavaBinder﹕ *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
        at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
        at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
        at android.database.AbstractWindowedCursor.getType(AbstractWindowedCursor.java:130)
        at com.example.android.leanback.PaginatedCursor.<init>(PaginatedCursor.java:65)
        at com.example.android.leanback.VideoDatabase.query(VideoDatabase.java:170)
        at com.example.android.leanback.VideoDatabase.getWordMatch(VideoDatabase.java:150)
        at com.example.android.leanback.VideoContentProvider.getSuggestions(VideoContentProvider.java:112)
        at com.example.android.leanback.VideoContentProvider.query(VideoContentProvider.java:85)
        at android.content.ContentProvider.query(ContentProvider.java:950)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
        at android.os.Binder.execTransact(Binder.java:446)

**Comment by JamieAndresakis** [comment]
There was a problem with the string used to build the query. I created my own db of content and removed the * from the query string and then everything worked fine
