### ISSUE TITLE
Custom Presenter Error: Do not setLayoutFrozen in layout or scroll 

### ISSUE THREAD

**Issue by Cataalinn** [googlesamples/androidtv-Leanback#62]
I had tried to create a custom presenter with just a single custom view and after first bind i get this error message. What's the problem?

```
03-02 21:59:23.772 21573-21573/com.nodomain.androidtvsample E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.nodomain.androidtvsample, PID: 21573
  java.lang.IllegalStateException: Do not setLayoutFrozen in layout or scroll
      at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2164)
      at android.support.v7.widget.RecyclerView.setLayoutFrozen(RecyclerView.java:1750)
      at android.support.v17.leanback.app.BaseRowFragment.onTransitionStart(BaseRowFragment.java:199)
      at android.support.v17.leanback.app.RowsFragment.onExpandTransitionStart(RowsFragment.java:483)
      at android.support.v17.leanback.app.BrowseFragment.startHeadersTransitionInternal(BrowseFragment.java:435)
      at android.support.v17.leanback.app.BrowseFragment.access$200(BrowseFragment.java:77)
      at android.support.v17.leanback.app.BrowseFragment$3.onRequestChildFocus(BrowseFragment.java:546)
      at android.support.v17.leanback.widget.BrowseFrameLayout.requestChildFocus(BrowseFrameLayout.java:124)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.support.v7.widget.RecyclerView.requestChildFocus(RecyclerView.java:2081)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.view.ViewGroup.requestChildFocus(ViewGroup.java:740)
      at android.support.v7.widget.RecyclerView.requestChildFocus(RecyclerView.java:2081)
      at android.view.ViewGroup.addViewInner(ViewGroup.java:4341)
      at android.view.ViewGroup.addView(ViewGroup.java:4145)
      at android.view.ViewGroup.addView(ViewGroup.java:4086)
      at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:591)
      at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
      at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6708)
      at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6666)
      at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6654)
      at android.support.v17.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1473)
      at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:111)
      at android.support.v17.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:364)
      at android.support.v17.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1696)
      at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:1881)
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3026)
      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2903)
      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)
      at android.view.View.layout(View.java:16630)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
      at android.view.View.layout(View.java:16630)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
      at android.view.View.layout(View.java:16630)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecorated(RecyclerView.java:7629)
      at android.support.v17.leanback.widget.GridLayoutManager.layoutChild(GridLayoutManager.java:1631)
      at android.support.v17.leanback.widget.GridLayoutManager.access$2700(GridLayoutManager.java:53)
      at android.support.v17.leanback.widget.GridLayoutManager$2.addItem(GridLayoutManager.java:1540)
      at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:124)
    at android.support.v17.leanback.widget.Grid.appendOneCol
```

**Comment by ryanseys** [comment]
I'm not sure what to say here. I'm going to need a bit more information. What modifications have you made? What code are you writing?

**Comment by Cataalinn** [comment]
So i'm trying to create a custom presenter which look something like this 

`public class LoopingVinePresenter extends Presenter {

    private static final int CARD_WIDTH = 170;
    private static final int CARD_HEIGHT = 376;
    private static int selectedColor, unselectedColor;

    @Override
    public LoopingVineViewHolder onCreateViewHolder(ViewGroup parent) {

        selectedColor = parent.getResources().getColor(R.color.selected_card);
        unselectedColor = parent.getResources().getColor(R.color.unselected_card);

        final LoopingVideo loopingVideo = new LoopingVideo(parent.getContext()) {
            @Override
            public void setSelected(boolean selected) {
                updateCardBackgroundColor(this, selected);
                super.setSelected(selected);
            }
        };

        loopingVideo.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View v, boolean hasFocus) {
                if (hasFocus) {
                    loopingVideo.startPlaying();
                } else {
                    loopingVideo.stopPlay();
                }
            }
        });

        loopingVideo.setFocusable(true);
        loopingVideo.setFocusableInTouchMode(true);
        updateCardBackgroundColor(loopingVideo, false);

        return new LoopingVineViewHolder(loopingVideo);
    }

    @Override
    public void onBindViewHolder(ViewHolder viewHolder, Object item) {
        Vine vine = (Vine) item;
        LoopingVideo video = ((LoopingVineViewHolder) viewHolder).loopingVideo;
        video.setVineDescription(vine);
        video.setMainImageDimensions(CARD_WIDTH, CARD_HEIGHT);
    }

    @Override
    public void onUnbindViewHolder(ViewHolder viewHolder) {
        LoopingVideo video = (LoopingVideo) viewHolder.view;
        video.stopPlay();
    }

    private static void updateCardBackgroundColor(LoopingVideo view, boolean selected) {
        int color = selected ? selectedColor : unselectedColor;
        //view.setBackgroundColor(color);
        //view.findViewById(R.id.vine_description).setBackgroundColor(color);
        //view.findViewById(R.id.vine_author_name).setBackgroundColor(color);
    }
}
`
where LoopingVideo is a BaseCardView extension who contains a TextureView that will play a Vine.
After initialisation of Presenter and setting all the info for it, after first bind (i saw that in debugger) i get that error. I don't know what's the problem.

**Comment by Cataalinn** [comment]
And still no answer..

**Comment by ryanseys** [comment]
Your Presenter implementation looks fine. It looks like you're running a layout/scroll during the enter animation call. The offending code block will likely be in the class that extends BrowseFragment or RowsFragment. Can you investigate those classes and if you still have issues, you may have to provide more source for us to investigate. 

As an aside, a developer has created a similar Vine app and their source is provided here which may provide some more help in developing your app: https://github.com/hitherejoe/Vineyard

**Comment by Fleker** [comment]
The 3p library [Leanback Cards](https://github.com/hitherejoe/LeanbackCards) can be used as a reference for creating a vine card.
