### ISSUE TITLE
Crash in BrowseSupportFragment because of BrowseSupportFragment.setHeadersState(BrowseSupportFragment.HEADERS_DISABLED)

### ISSUE THREAD

**Issue by michaelrhughes** [googlesamples/androidtv-Leanback#76]
I am experiencing a crash after updating from 23.3.0 to 24.0.2 when I launch the _BrowseSupportFragment_. 

On the _BrowseSupportFragment_ I need the headers on the left hand pane to be gone so I call _setHeadersState(BrowseSupportFragment.HEADERS_DISABLED);_. In the _onStart()_ method there is a call to _mMainFragment.getView()_. But this fragment has not yet been created. I see that this fragment can be created when a user calls setAdapter IF there is an adapter set with a size > 0. My data comes from the network so it will only be available some time after _onStart()_.

```

FATAL EXCEPTION: main
   Process: my.package.name, PID: 20818
   java.lang.RuntimeException: Unable to start activity ComponentInfo{my.package.name}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.support.v4.app.Fragment.getView()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.support.v4.app.Fragment.getView()' on a null object reference
    at android.support.v17.leanback.app.BrowseSupportFragment.onStart(BrowseSupportFragment.java:1512)
    The rest of the stack trace is in my code
```

**Comment by michaelrhughes** [comment]
It looks like this issue might be happening because I:
1) Don't have my data until it is downloaded from the network
and
2) I don't have visible headers.

**Comment by michaelrhughes** [comment]
I have confirmed the issue is due to disabling the headers in the app. If I don't disable them everything works. But this is not a fix as I need the headers hidden.

**Comment by philipgiuliani** [comment]
Related issue @ android issue tracker: https://code.google.com/p/android/issues/detail?id=214795

**Comment by michaelrhughes** [comment]
@philipgiuliani thanks! This is really helpful. I'll try to come up with a workaround by using an adapter with a blank view in it to see if that helps.

**Comment by nikbjork** [comment]
any update on this? been trying to work around it but without any success

**Comment by Fleker** [comment]
No update in the issue tracker, but starring it would lead to greater priority among the devs

**Comment by philipgiuliani** [comment]
Yep please star the issue!
This is the new link: https://code.google.com/p/android/issues/detail?id=223942
They closed it, so we reopened a new one.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
