### ISSUE TITLE
Reloading data in BrowseFragment

### ISSUE THREAD

**Issue by j-garin** [googlesamples/androidtv-Leanback#80]
Hi. I am writing an Android TV app and have bumped into this issue. I have to replace all the rows in BrowseFragment with new ones on receiving an Event. What i've tried:
```
mRowsAdapter.clear();
...
mRowsAdapter.add(add new rows here);
```
Where mRowsAdapter is the ArrayObjectAdapter with ListRow items. Also tried this approach:
```
mRowsAdapter = new ArrayObjectAdapter(new ListRowPresenter());
setAdapter(mRowsAdapter);
mRowsAdapter.add(add new rows here);
```
Neither of them works. I keep getting IOBE. Here are the logs:

```
            java.lang.IndexOutOfBoundsException: Index: 7, Size: 0
                                   at java.util.ArrayList.get(ArrayList.java:411)
                                   at android.support.v17.leanback.widget.ArrayObjectAdapter.get(ArrayObjectAdapter.java:56)
                                   at android.support.v17.leanback.app.ListRowDataAdapter.get(ListRowDataAdapter.java:65)
                                   at android.support.v17.leanback.widget.ItemBridgeAdapter.getItemViewType(ItemBridgeAdapter.java:248)
                                   at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5046)
                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5172)
                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
                                   at android.support.v17.leanback.widget.GridLayoutManager.getViewForPosition(GridLayoutManager.java:971)
                                   at android.support.v17.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1464)
                                   at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:111)
                                   at android.support.v17.leanback.widget.Grid.appendVisibleItems(Grid.java:371)
                                   at android.support.v17.leanback.widget.GridLayoutManager.appendVisibleItems(GridLayoutManager.java:1702)
                                   at android.support.v17.leanback.widget.GridLayoutManager.fastRelayout(GridLayoutManager.java:1764)
                                   at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:1888)
                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.support.v17.leanback.widget.ScaleFrameLayout.onLayout(ScaleFrameLayout.java:172)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                   at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                   at android.view.View.layout(View.java:17519)
                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                   at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                   at android.view.Choreographer.doFrame(Choreographer.java:619)
com.cloudify E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                   at android.os.Handler.handleCallback(Handler.java:751)
                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                   at android.os.Looper.loop(Looper.java:154)
                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                   at java.lang.reflect.Method.invoke(Native Method)
                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
Original question on [stackoverflow](http://stackoverflow.com/questions/40266159/android-tv-reloading-data-in-browsefragment)
Please help. Thank you.

**Comment by Fleker** [comment]
There is a refreshUI method in the LeanbackFragment class which seems to
handle this type of use pretty well.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
