### ISSUE TITLE
Java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

### ISSUE THREAD

**Issue by Allan-Nava** [googlesamples/androidtv-Leanback#93]
I have this error when I navigate to each RowFragments.

```
 E/AndroidRuntime: FATAL EXCEPTION: Thread-24
                                                                      Process: it.sportube.sportubetv, PID: 3025
                                                                      java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                                          at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2530)
                                                                          at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4903)
                                                                          at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11123)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6731)
                                                                          at android.support.v17.leanback.widget.ItemBridgeAdapter$1.onItemRangeInserted(ItemBridgeAdapter.java:156)
                                                                          at android.support.v17.leanback.widget.ObjectAdapter$DataObservable.notifyItemRangeInserted(ObjectAdapter.java:92)
                                                                          at android.support.v17.leanback.widget.ObjectAdapter.notifyItemRangeInserted(ObjectAdapter.java:199)
                                                                          at android.support.v17.leanback.widget.ArrayObjectAdapter.add(ArrayObjectAdapter.java:100)
                                                                          at android.support.v17.leanback.widget.ArrayObjectAdapter.add(ArrayObjectAdapter.java:88)
                                                                          at it.sportube.sportubetv.fragment.LegaProFragment$1.onSuccess(LegaProFragment.java:92)
                                                                          at it.sportube.sportubetv.api.SportubeApiClient$11.run(SportubeApiClient.java:587)
                                                                          at java.lang.Thread.run(Thread.java:761)
```

![unnamed 1](https://user-images.githubusercontent.com/22498435/29816614-0a90c0a6-8cb5-11e7-83eb-581bd2ec3d47.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
