### ISSUE TITLE
 rowPresenter.setHoverCardPresenterSelector(new HoverPresenterSelector());

### ISSUE THREAD

**Issue by raazvengala** [googlesamples/androidtv-Leanback#94]
setHoverCardPresenter is giving null pointer exception.

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.offsetDescendantRectToMyCoords(android.view.View, android.graphics.Rect)' on a null object reference
                                                                                 at android.support.v17.leanback.widget.HorizontalHoverCardSwitcher.select(HorizontalHoverCardSwitcher.java:71)
                                                                                 at android.support.v17.leanback.widget.ListRowPresenter.selectChildView(ListRowPresenter.java:506)
                                                                                 at android.support.v17.leanback.widget.ListRowPresenter$1.onChildSelected(ListRowPresenter.java:448)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.dispatchChildSelected(GridLayoutManager.java:922)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager$2.createItem(GridLayoutManager.java:1554)
                                                                                 at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:113)
                                                                                 at android.support.v17.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:366)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1744)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2027)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:8839)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.layoutChild(GridLayoutManager.java:1681)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager$2.addItem(GridLayoutManager.java:1589)
                                                                                 at android.support.v17.leanback.widget.SingleRow.appendVisibleItems(SingleRow.java:126)
                                                                                 at android.support.v17.leanback.widget.Grid.appendOneColumnVisibleItems(Grid.java:366)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.appendOneColumnVisibleItems(GridLayoutManager.java:1744)
                                                                                 at android.support.v17.leanback.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:2027)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.support.v17.leanback.widget.ScaleFrameLayout.onLayout(ScaleFrameLayout.java:172)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
                                                                                 at android.view.View.layout(View.java:15806)
                                                                             	at android.view.ViewGroup.layout(Vi

**Comment by raazvengala** [comment]
setHoverCardPresenter is giving null pointer exception. 
It's not working and also there is no information in developer.android.com also. But latest Android Box which are certified by google has this working Hover Card View. Can someone please solve this.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
