### ISSUE TITLE
Crash MP4 by http    - java.lang.IllegalArgumentException: Unsupported media rate.

### ISSUE THREAD

**Issue by GuzunAlx** [googlesamples/androidtv-Leanback#96]
Crash playback file
https://yadi.sk/i/rQ4vx8tn3MsEpX

     java.lang.IllegalArgumentException: Unsupported media rate.
                                                                              at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseEdts(AtomParsers.java:803)
                                                                              at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:91)
                                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:333)
                                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:276)
                                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:267)
                                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)

This file work fine with MediaPlayer

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
